[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fdf"
version = "0.1.0"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
include = ["fdf*"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.mypy]
strict = true
ignore_missing_imports = true

[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
ignore = ["UP035", "UP045"]